

import numpy as np




CHANNEL_NAMES = ['FC3', 'FCz', 'FC4', 'C5', 'C3', 'C1', 'Cz', 'C2', 'C4', 'C6', 'CP5', 'CPz', 'CP6', 'P3', 'Pz', 'P4']
FREQ_S = 128.0
NUM_CHANNELS = 16
LEN_DATA_CHUNK = 4.0
LEN_RIGHT_SEC = 4.0
LEN_LEFT_SEC = 4.0
LEN_IDLE_SEC = 3.0
LEN_PERIOD_SEC = LEN_IDLE_SEC + LEN_RIGHT_SEC + LEN_IDLE_SEC + LEN_LEFT_SEC
LEN_COLOR_CONV_SEC = 2.0
LEN_REST_ESTIM_SEC = LEN_PERIOD_SEC
LEN_REC_SEC = 10.0 * LEN_PERIOD_SEC
LEN_REC_BUF_SEC = 1.2 * LEN_REC_SEC

NUM_EVENT_TYPES = 4     # r, l, idle, calib
M_FIR = 32
LEN_PADDING = M_FIR / LEN_DATA_CHUNK
IMP_RESP_LEN = 2 * FREQ_S/LEN_DATA_CHUNK
FEAT_MULT_1_SIMU = 0.002
FEAT_MULT_2_SIMU = 1.0
FEAT_MULT_1_REAL = 0.001
FEAT_MULT_2_REAL = 1.0
IMAGE_W = 960
IMAGE_H = 640
#CURSOR_COLOR_REST = 'green'
#CURSOR_COLOR_RIGHT = 'red'
#CURSOR_COLOR_LEFT = 'blue'
#CURSOR_COLOR_IDLE = 'black'
CURSOR_COLOR_REST = np.array([0, 127, 0])    # RGB
CURSOR_COLOR_RIGHT = np.array([255, 0, 0])
CURSOR_COLOR_LEFT = np.array([0, 0, 255])
CURSOR_COLOR_IDLE = np.array([0, 0, 0])